import time
t=1
print("Start Hacking Nasa.....")
time.sleep(t)
print("Hacking NASA 0%...")
time.sleep(t)
print("Hacking NASA 10%...")
time.sleep(t)
print("Hacking NASA 30%...")
time.sleep(t)
print("Hacking NASA 50%...")
time.sleep(t)
print("Hacking NASA 70%...")
time.sleep(t)
print("Hacking NASA 85%...")
time.sleep(t)
print("Hacking NASA 100%...")
time.sleep(t)
print("NASA Hacked Successfully !")
